spring.application.name=Maychu
# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/examguardhai
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
123456
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Thymeleaf
spring.thymeleaf.cache=false

# Session timeout 8 tiếng
server.servlet.session.timeout=480m
storage.upload-dir=/opt/examguard/uploads
google.drive.credentials-path=/opt/examguard/credentials.json
google.drive.folder-id=https://drive.google.com/drive/folders/1DaiPDYRG-aPKjw51TBSOxO1kexI45aea?usp=drive_link